{
 "title": "Cloud",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Load avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{hostname=~\"cld.+\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{hostname=~\"cld.+\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Net",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth0\",hostname=~\"cld.+\"}[2m])*8",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "HDD Root",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",hostname=~\"cld.+\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "HDD Home",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/home\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (hostname) (node_hwmon_temp_celsius{hostname=~\"cld.+\"}) ",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "HDD Root IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"md1\",hostname=~\"cld.+\"}[2m])",
     "legendFormat": "{{hostname}} r"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"md1\"}[2m])",
     "legendFormat": "{{hostname}} w"
    }
   ]
  },
  {
   "title": "HDD Home IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"md2\",hostname=~\"cld.+\"}[2m])",
     "legendFormat": "{{hostname}} r"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"md2\"}[2m])",
     "legendFormat": "{{hostname}} w"
    }
   ]
  }
 ]
}