name: CI
on:
  workflow_dispatch: {}

jobs:
  check_services:
    name: Check service ${{ matrix.service }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        service:
          - sesame
          - office
      fail-fast: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup service ${{ matrix.service }}
      run: (cd ./services/${{ matrix.service}} && docker-compose pull && docker-compose build && docker-compose up --build -d)

    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5

    - name: Setup checker libraries
      run: if [ -f checkers/${{ matrix.service }}/requirements.txt ]; then python -m pip install -r checkers/${{ matrix.service }}/requirements.txt; fi

    - name: Test checker on service
      run: checkers/${{ matrix.service }}/checker.py TEST 127.0.0.1

